version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 805392809179.dkr.ecr.ap-south-1.amazonaws.com
 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecr-cicd .
      - docker tag ecr-cicd:latest 805392809179.dkr.ecr.ap-south-1.amazonaws.com/ecr-cicd:2 
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 805392809179.dkr.ecr.ap-south-1.amazonaws.com/ecr-cicd:2
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
  post_build:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon EKS...
      - aws eks --region ap-northeast-2 update-kubeconfig --name EKScluster1
      

